Make the code runnable and formatted using Black
CALIPSO-project/SPINacc pull request #33
Opened 2024-04-18 14:47 UTC by tztsai

I fixed some small errors in the code so that task 1, 2, 4, 5 can run successfully. Then I used `Black` to automatically format the code. Finally, I updated `.gitignore` and removed `*.pyc` files.

2024-04-26 09:31 UTC, ma595 requested changes

2024-04-26 09:31 UTC, ma595 commented on DEF_Trunk/MLacc.def
Why delete this file?

2024-04-26 09:31 UTC, ma595 commented on DEF_Trunk/varlist.json
why delete this file?

2024-04-26 09:31 UTC, ma595 commented on AuxilaryTools/mysimulations_specs
probably best not to delete see below

2024-04-26 09:31 UTC, ma595 commented on tests/config.py
why is this deleted?

2024-04-26 09:31 UTC, ma595 commented on requirements.txt
After reviewing this again, the error for me (on MacOS emerges with python 3.9 pulling in an older version of numpy (1.17) for scipy 1.5.0. It's possible it works for older versions of python on linux.

2024-04-26 10:22 UTC, tztsai commented on DEF_Trunk/MLacc.def
I used `git rm --chached` to prevent git from tracking my changes of the paths. I think these config files should not be deleted. But how do I let git ignore my local changes then? Adding them to `.gitignore` does not work as they are already tracked by git.

2024-04-26 13:52 UTC, tztsai commented on AuxilaryTools/mysimulations_specs.py
I used `git mv` and then reformatted the file using `Black`, but it has made no difference.

2024-05-01 13:07 UTC, ma595 commented on requirements.txt
An error emerges in the evaluation step when `set_xticklabels("")` is set with `matplotlib==3.8.4`, but it works when `matplotlib` is rolled back to `3.2.2`. I have removed the line, and now the figure is created without error.

2024-05-01 16:26 UTC, ma595 commented on requirements.txt
Also, when running step 2, numpy `ndarrays` have changed at some point between 1.22.4 and 1.26.4 and `Jagged` arrays aren't possible without the setting `dtype=object` i.e.:

`np.array([adict["PFT%iClusD" % ii]["clus_01_loc"] for ii in kpfts], dtype=object)`

2024-05-01 16:31 UTC, ma595 commented on requirements.txt
And finally, the API to `BaggingRegressor` in `train.py` has also changed. `base_estimator` has been renamed to `estimator`. 

Can you confirm my findings? i.e. With the latest packages as set in `requirements.txt` the above errors occur, and the fixes make sense. I therefore think we should leave the `requirements.txt` changes to another PR (or we do the minimum set of changes to `requirements.txt` only in order to make it `runable`.

2024-05-21 12:31 UTC, ma595 submitted a review, later dismissed

2024-05-21 13:25 UTC, ma595 requested changes

2024-05-21 13:25 UTC, ma595 commented on DEF_Trunk/varlist_explained.md
It might be better to put this in a separate PR.

2024-05-22 14:47 UTC, ma595 approved these changes

2024-05-22 16:47 UTC, merged